apply_preset:
  name: '{{ "service.apply_preset.name" }}'
  description: '{{ "service.apply_preset.description" }}'
  fields:
    preset_name:
      name: '{{ "service.apply_preset.fields.preset_name.name" }}'
      description: '{{ "service.apply_preset.fields.preset_name.description" }}'
      required: true
      example: "Movie Time"
      selector:
        text:
